### ISSUE TITLE
OpenAQ air quality data layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#113]
https://openaq.org would be a great layer to add!

**Comment by avsingh999** [comment]
@jywarren Can I work on it.
Thanks : )

**Comment by jywarren** [comment]
That would be wonderful!!!

**Comment by avsingh999** [comment]
Hi, @jywarren  Sorry For late I was Busy in My Academics. Can You please Guide Me How to Do this.
Thank you :)

**Comment by avsingh999** [comment]
@jywarren @sagarpreet-chadha  please guide me to solve this issue I don't know how to start.
Thank you  :)

**Comment by gauravano** [comment]
Hey @avsingh999, I haven't worked on this repository much but you can get started by looking at old PRs of this repository like this one - https://github.com/publiclab/leaflet-environmental-layers/pull/17/. there are many PR's where layer addition has been done, so going through them will give you a idea. 

Or, you can wait for Sagarpreet and Jeff.

Thanks!

**Comment by avsingh999** [comment]
@gauravano  Thank you : )

**Comment by sagarpreet-chadha** [comment]
Hi @avsingh999 😄 !

I agree with @gauravano , there are plenty of examples you can go through to add this new layer . 
The API documentation also looks very nice for this layer : https://docs.openaq.org/ 
Thank you !

**Comment by avsingh999** [comment]
@jywarren @sagarpreet-chadha @gauravano  I am using this API like as " Air Quality Index " because both API give same parameters data But in OpenAQ API when I was getting data  using this 'https://api.openaq.org/v1/latest' but I am getting the lot of data in the same coordinate you can see this for particular coordinates '

> https://api.openaq.org/v1/latest?coordinates=50.428997,4.4586806

So I want to know how should I show this data for perticular coordinates becuase there are lot of data for  this coordinate

Thanks : )

'

**Comment by avsingh999** [comment]
@jywarren @sagarpreet-chadha  please help me. : )

**Comment by jywarren** [comment]
I'm sorry I missed this but it looks like you figured it out and it looks great! Thanks so much!!!
