### ISSUE TITLE
Add EWG's PFA pollution map as a layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#119]
https://www.ewg.org/research/update-mapping-expanding-pfas-crisis

![image](https://user-images.githubusercontent.com/24359/53037745-db5e2c00-342f-11e9-9dcb-a63a48fba067.png)

**Comment by ephemeralwaves** [comment]
I would like to work on this!

**Comment by gauravano** [comment]
hey @ephemeralwaves, go ahead! Thanks!

Really liked your notes :100:. @jywarren do check it.

**Comment by jywarren** [comment]
Yeah this is great!

**Comment by jywarren** [comment]
Do they have a map layer we could include directly which could be easier than geocoding? Just wondering!

**Comment by ephemeralwaves** [comment]
> Do they have a map layer we could include directly which could be easier than geocoding? Just wondering!

I looked on the EWG site. They use mapbox and in the src under scripts it looks like they geocode. It was helpful though to look there because both there is a  [PFAS geojson file](https://www.ewg.org/interactive-maps/2017_pfa/PFAS_7_19_2018.geojson) and an [EPA tap water detections geojson file](https://www.ewg.org/interactive-maps/2017_pfa/UCMR_systems_1_2_2019.geojson) that can be used. Not sure if/how mapbox and leaflet can interact yet, but it looks like in terms of geocoding, the PFAS data does need to be geocoded.

**Comment by jywarren** [comment]
Yes, mapbox is built on leaflet so they should be compatible!

**Comment by ephemeralwaves** [comment]
I have the PFAS layer working for US contamination sites. I'm not sure how code review works but here is the [working example](https://thinkcolorful.org/leaflet-environmental-layers/example/index.html#4/48.78/-93.60/BL2-PFAS) of my layer implemented via [my repository](https://github.com/ephemeralwaves/leaflet-environmental-layers).  Feedback is appreciated. I'm also not sure if I should expand this to include international sites or not as the EWG site doesn't do this. Also EWG shows data from the EPA which I'm not sure if I'm supposed to include but I'd imagine that would be its own separate layer.

**Comment by jywarren** [comment]
Hi! Oh great -- would you like to open a pull request or have you already?
Thank you!!!

**Comment by ephemeralwaves** [comment]
Just opened a PR!

**Comment by jywarren** [comment]
Ah! linking to https://github.com/publiclab/leaflet-environmental-layers/pull/154 where this was solved! Thanks!
