### ISSUE TITLE
Weekly community Check-In #28 - Teamwork

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#231]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

**This Week's Theme:**

**Teamwork**

"Alone we can do so little; together we can do so much."
While working on any big open source project, team work and collaboration is key to successfully  getting work done. 
Share an issue which you solved recently/working on along with other members of PL.

The issue I worked on recently related to standardization of layer code in LEL was a great learning experience and collaboration and teamwork with my mentors to solve it !!

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by ananyaarun** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @aSquare14 @vaarigupta @alonpeer @pdurbin @HarshKhandeparkar @aashna27 @harshithpabbati @niravasher @jesus-montano @michelelong @cryptoclidus @mohamed-elalem @konolga
--

**Comment by ananyaarun** [comment]
@aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @michelelong @cryptoclidus @mohamed-elalem @konolga

**Comment by gautamig54** [comment]
Great topic for the check-in @ananyaarun, "Teamwork"!
I have been inactive for the past two weeks due to medical issues, but I am all set to join back and work . I have missed quite a few issues and I am updating myself now. 
I have been collaborating with @CleverFool77 for the past one and a half month and its been a great learning experience. I have got great help and support from my mentors @jywarren @gauravano @SidharthBansal . A special thanks to @jywarren for constantly motivating me and checking on me. 
One of the most appealing quality of PublicLab is its amazing teamwork. Everyone here is always looking out to help one and another with a lot of zeal which has resulted in having more than 500 contributors. 
I am currently working on pending issues #5890, #5733 and #5708. 
@CleverFool77 and I have started the discussion on the new issue #5891. We will be discussing more about that on the open call tomorrow. 
I am also aiming to open a few FTOs this week and complete all my pending tasks as soon as possible. 
Apologies to @CleverFool77 and @jywarren for the delay. 
Looking forward to have a great week ahead. 
Happy Coding!! :D

**Comment by gauravano** [comment]
Hi everyone,

Nice theme @ananyaarun! 

Hmm, there are so many to share. This is one which I enjoyed most https://github.com/publiclab/plots2/issues/1934 because it took time, frustrated me but I learnt. 

Also, if you're waiting for a review then feel free to mention me or @jywarren in respective Gitter channels. I hope everyone knows that we have repo-specific Gitter channels now - https://gitter.im/publiclab/image-sequencer
https://gitter.im/publiclab/leaflet - For all leaflet based projects
https://gitter.im/publiclab/mapknitter
https://gitter.im/publiclab/simple-data-grapher

Have a great week :100:

**Comment by aSquare14** [comment]
@ananyaarun Great topic ! Public Labs has amazing teamwork. It is one of the most helpful communities and has helped me grow a lot. By mentoring in GCI and now GSoC, by reviewing PRs and creating FTOs, I have learnt a lot ! 👍 
Have an amazing week everyone ! Get well soon @gautamig54 :)

**Comment by sagarpreet-chadha** [comment]
Completely agreed with @ananyaarun , it was great fun to debug that issue in LEL . Glad we found it :)
Looking forward for more collaboration in the near future!
Thank you

**Comment by jywarren** [comment]
Hi all! I am feeling all warm and fuzzy seeing everyone's work begin to integrate and connect - from MapKnitter to leaflet-environmental-layers to Leaflet.DistortableImage to image-sequencer and more! That's teamwork for you!

Also - i just opened PR 6000 on plots2 ❤️ 

https://github.com/publiclab/plots2/pull/6000

**Comment by CleverFool77** [comment]
Hi everyone, 
Me and @gautamig54 ar working on plots design revamp.
It had been great collaboration and experience so far. Cheers to constant discussions with our ideas and and amazing team @gautamig54 . 
And Thanks @jywarren For clearing out custom search results feature. I guess I pestered you a lot in that. Thanks for being patient :heart:

**Comment by kaustubh-nair** [comment]
Hi all!
Since @alaxalves and I are working on the same project, we're collaborating together almost all the time!
We've helped each other out on our PR's whenever one of us is stuck, and that makes fixing issues much easier!

This week I've been a little inactive since I was a bit ill. But I'm better now so I'm going to get back on the Mapknitter upgrade.
This week I'll be finishing setting up codecov on Plots2 https://github.com/publiclab/plots2/pull/5954 and fix the codecov inconsistencies on Mapknitter https://github.com/publiclab/mapknitter/issues/810
Also I'll get started with the ruby 2.5 upgrade on Mapknitter so we can start with Rails 6!
Thanks!

**Comment by divyabaid16** [comment]
Hi everyone!
Great theme @ananyaarun and even I feel that Teamwork is the strength of Public Lab. From day one, I have seen this and I learned many things just by being the part of the discussion. Recently I had collaborated with @sashadev-sky and @jywarren for the multiple image export. Currently, I have been doing UI fix in Mapknitter. 

GSoC Updates:

PR's created:
https://github.com/publiclab/mapknitter/pull/825
https://github.com/publiclab/mapknitter/pull/821
https://github.com/publiclab/mapknitter/pull/820
https://github.com/publiclab/mapknitter/pull/801

PR's merged:
https://github.com/publiclab/mapknitter/pull/802
https://github.com/publiclab/mapknitter/pull/799

**Comment by alaxalves** [comment]
Hi all.
I think that one of PublicLab's "attributes" is the great teamwork spirit we have. Since I have been working with this great team I had the opportunity to work with several members in several different stuff, including my GSoC partner @kaustubh-nair. During Rails 5, I worked collaboratively mostly with @kaustubh-nair and @sashadev-sky.

This past week I have fixed https://github.com/publiclab/mapknitter/issues/791 along with @jywarren's help. I have also finished Rails 5 upgrade and pushed it to `unstable` branch. @kaustubh-nair took charge to fix the bugs the come to happen with Rails 5. Then I have started working with Rails 6 upgrade, but before this I need to upgrade to Rails > 2.5 and the upcoming debian issues.

**Merged PRs:**
- https://github.com/publiclab/mapknitter/pull/795
- https://github.com/publiclab/mapknitter/pull/794
- https://github.com/publiclab/mapknitter/pull/685
- https://github.com/publiclab/mapknitter/pull/803

**Opened PRs:**
- https://github.com/publiclab/mapknitter/pull/824

**Issues to fix:**
- https://github.com/publiclab/mapknitter/issues/831
- https://github.com/publiclab/mapknitter/issues/732

**Comment by gauravano** [comment]
Anyone interested in opening next weekly check-in?

**Comment by ViditChitkara** [comment]
I'm interested!

**Comment by gauravano** [comment]
Great!

**Comment by gauravano** [comment]
New check-in open at https://github.com/publiclab/mapknitter/issues/851. Thank you @ViditChitkara :tada:
