### ISSUE TITLE
Make layer names listing in README and layers hash strings consistent

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#297]
It seems we list out layer names here:

https://github.com/publiclab/leaflet-environmental-layers#layers

And then we do it differently here:

https://github.com/publiclab/leaflet-environmental-layers/blob/9456be438a71da73f493475377f2e4cb3458d1be/src/AllLayers.js#L9-L15

I made a mistake embedding this map because I used the wrong string convention. Let's standardize them and correct the ones in the readme!

https://publiclab.org/wiki/inline-maps#Maps+with+preset+layers

Any help appreciated!

**Comment by jywarren** [comment]
@crisner this plus some more documentation/cleanup would also allow you to link from your embed code generating demo to a central place where the layer names and such are documented. In case you like that idea!

**Comment by crisner** [comment]
@jywarren, Should we change only the layer names in the readme to match the ones in the AllLayers.js file? Or should we follow a standard convention, like camelcase, which would mean correcting a few ones in the AllLayers.js file as well?

**Comment by jywarren** [comment]
Let's start by getting the README ones correct, and do the standardization in a separate issue? We'll need to watch out that we aren't breaking downstream uses, it's almost like the current layer names are an API and we need to respect how they're used downstream.

I'm almost tempted to say they should now be case-insensitive so that we purposely retain backwards compatibility? What do you think?

**Comment by crisner** [comment]
That sounds great! Shall I make an fto issue out if this? It seems like a good candidate as the task is narrowed down to matching the layer names.

**Comment by crisner** [comment]
@jywarren, Looks like the readme follows the naming convention from the layers.js file?
https://github.com/publiclab/leaflet-environmental-layers/blob/15477e9b925863c5595da84a76d31393148ad720/example/layers.js#L124-L171

Also, the layer names in the demo page's URL follows:
https://github.com/publiclab/leaflet-environmental-layers/blob/15477e9b925863c5595da84a76d31393148ad720/example/layers.js#L173-L225

Shouldn't all of this match? I think at least the section responsible for URL names in the demo page in layers.js should also match so that the layer names in the hash strings are consistent.

**Comment by jywarren** [comment]
I agree all should match! And yes, this could be a nice FTO as long as we check we don't break any downstream uses :-)

Thank you!

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren , @crisner 
Please note we have to follow layer names as specified in **allLayer.js**  all over LEL. Thanks!
