### ISSUE TITLE
Display new layers menu when instantiating LEL with one liner code

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#347]
The new layers browser menu has only been implemented in the demo. We will need to implement it to be displayed when instantiating LEL with the 'one-liner' code.

**Comment by crisner** [comment]
@jywarren, do we need to retain the default layer control? I don't think we would need it anymore as we have simplified the layers browser menu for smaller screens. I was planning to replace it but we could add an option if we want the default one to be displayed when we need it. What do you think?

**Comment by crisner** [comment]
This for the code that is used to integrate LEL into plots2.

**Comment by jywarren** [comment]
This is great. The default is minimal to the point of being super confusing; see this page for example: https://stable.publiclab.org/map

![image](https://user-images.githubusercontent.com/24359/72450742-d8c39e00-3788-11ea-970a-7f42110879b2.png)

So, let's ditch it? Or if it's a big project, let's just leave the code there and... advise against it? we don't want people to feel they MUST use our browser if their use case is really different, i guess.  

Also: the one-liner should be the default constructor, because it's so great! It's a bit buried in the README right now. What do you think?

https://github.com/publiclab/leaflet-environmental-layers#add-all-lel-layers-at-once

**Comment by crisner** [comment]
@jywarren, I couldn't find your comment where you mentioned how the one-liner code should be the way to implement LEL and that it was buried deep in the readme file. So I am replying to that here. I am thinking we could either move the code to the top or move the other documentation to a docs file leaving only the one-liner code in the readme. What do you think?

**Comment by crisner** [comment]
Ah!!! The comment I was looking for was right here! :laughing: Sorry about that!

**Comment by sagarpreet-chadha** [comment]
Agreed with @jywarren , the readme.md file is very large. 
We should have links to different markdown files in the main Readme.md file.
Something like: 

### Content
1. What is LEL
2. Terminologies
3. Get started
4. About Layers
5. One liner syntax
6. embed
7. custom control Bar
8. Hash
9. Testing
10. How to contribute?
11. Reach out the maintainers
12. About PublicLab

What do you think?

**Comment by jywarren** [comment]
I love this. We can even rename it to just be "basic usage" vs "one-liner"
and then start calling any other usage "adding layers individually"? it
kind of resets what the default is.

**Comment by crisner** [comment]
Awesome!
