### ISSUE TITLE
Second map inheriting values from first map

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#395]
I ran into an issue writing tests for maps and discovered that there was some issues that could be seen in `example/multipleMaps.html`. using this code:
```
      var bounds = new L.LatLngBounds(
        new L.LatLng(84.67351257, -172.96875),
        new L.LatLng(-54.36775852, 178.59375)
      );

      var map = L.map("map", {
        maxBounds: bounds,
        maxBoundsViscosity: 0.75,
      }).setView([43, -83], 3);
      map.options.minZoom = 3;

      var map2 = L.map("map2", {
        maxBounds: bounds,
        maxBoundsViscosity: 0.75,
      }).setView([43, -83], 3);
      map2.options.minZoom = 3;

      L.LayerGroup.EnvironmentalLayers({
        include: ['odorreport', 'asian', 'clouds', 'eonetFiresLayer', 'Unearthing', 'PLpeople'],
        addLayersToMap: true,
        hash: false,
      }).addTo(map);

      L.LayerGroup.EnvironmentalLayers({
        // simpleLayerControl: true,
        // include: ['odorreport', 'asian', 'clouds', 'eonetFiresLayer', 'Unearthing', 'PLpeople'],
        hash: false,
      }).addTo(map2);
```
I found that the first map's `addLayersToMap: true` was being carried forward into map2, since it did not have anything set for `addLayersToMap` - it wasn't setting it to the default.

**Comment by nstjean** [comment]
I didn't get a screenshot because loading ALL layers froze my browser.

**Comment by crisner** [comment]
Nice catch! Console logs seem to be giving the expected values. I had to expand them to see that they were indeed being carried over.

![consoleOutput1](https://user-images.githubusercontent.com/29401459/74215687-e573dd00-4cc7-11ea-92c2-e19f06bba747.png)

 It looks like the way we are initializing options is the issue. I had intended to change this later because it wasn't causing any issues at the time. Leaflet uses `L.Util.setOptions(this, options);` to set options. This also helps to reduce some number of lines in our LEL code. This is what I got after using Leaflet's methods.
![consoleOutput2](https://user-images.githubusercontent.com/29401459/74215797-59ae8080-4cc8-11ea-807b-e3bbef4cddcc.png)

This was the code used for the above screenshots:
```js
var bounds = new L.LatLngBounds(
        new L.LatLng(84.67351257, -172.96875),
        new L.LatLng(-54.36775852, 178.59375)
      );

      var map = L.map("map", {
        maxBounds: bounds,
        maxBoundsViscosity: 0.75,
      }).setView([43, -83], 3);
      map.options.minZoom = 3;

      var map2 = L.map("map2", {
        maxBounds: bounds,
        maxBoundsViscosity: 0.75,
      }).setView([43, -83], 3);
      map2.options.minZoom = 3;

      L.LayerGroup.EnvironmentalLayers({
        simpleLayerControl: false,
        include: ['odorreport', 'asian', 'clouds', 'eonetFiresLayer', 'Unearthing', 'PLpeople'],
      }).addTo(map);
      
      L.LayerGroup.EnvironmentalLayers({
        simpleLayerControl: true,
        // addLayersToMap: true,
        // include: ['odorreport', 'asian', 'clouds', 'eonetFiresLayer', 'Unearthing', 'PLpeople'],
      }).addTo(map2);
```

This is what I got using the code from the issue description.
![consoleOutput3](https://user-images.githubusercontent.com/29401459/74215967-f3762d80-4cc8-11ea-81db-b8f3769f9afb.png)

**Comment by nstjean** [comment]
Excellent, I saw your suggestions in #396 I'll make sure it works correctly and push up the changes!
