### ISSUE TITLE
FracTracker csv seems broken?

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#68]
I'm seeing an error on https://publiclab.org/maps, when i turn it on:

```
rw.m @ util.js:224
2sagarpreet-chadha.github.io/FractrackerCSV.json:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

This also occurs here: https://publiclab.github.io/leaflet-environmental-layers/example/index.html#14/41.8720/-87.6378

Do you know why? Also, is this based from a static file and could we start to source it from some kind of dynamic source? 

Is it static because we need to parse a CSV? 

Thank you!!

The source seems to be here: https://github.com/publiclab/leaflet-environmental-layers/blob/master/src/fractracker.js

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
Its because of this - http in url of image instead of https . 
https://github.com/publiclab/leaflet-environmental-layers/blob/640fd942d7235ee93f7f25e5dbd32e3ff24d6857/src/fractracker.js#L3

Doing the changes now 👍 .

Yes the source was CSV --- hence i had converted it to JSON and hosted on github pages .

**Comment by sagarpreet-chadha** [comment]
And if one is using any **ad-blocker** then currently the markers might not appear due to http in url .

**Comment by jywarren** [comment]
ah, ok, thanks. But is the original CSV source dynamically generated? I
think we can come up with a parser to directly read it, as well, so that as
new data is published on their API, we can fetch it too!

Can you link us back to the original issue where this API is documented?
Thanks!
