### ISSUE TITLE
Bug: Jquery script being loaded multiple times.

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/leaflet-environmental-layers#95]
I was testing out the maps and saw this occur:

![jquerymultipleloads](https://user-images.githubusercontent.com/44309027/49352834-e353ce80-f67f-11e8-8f0a-24b66018c70f.gif)

I am not too sure about its effect on performance, but I think we could just add `<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>` to index.html and then edit the use of the script in each layer.

I believe lines like this are the culprit. Every layer has them and I suggest we remove them.

https://github.com/publiclab/leaflet-environmental-layers/blob/db25167538da307a5cc2b2ad279ba347a0dda17b/src/toxicReleaseLayer.js#L51-L53

https://github.com/publiclab/leaflet-environmental-layers/blob/db25167538da307a5cc2b2ad279ba347a0dda17b/src/toxicReleaseLayer.js#L65

**Comment by kevinzluo** [comment]
Ahhh. I see.
Maybe we can check if it has been loaded each time? Maybe something like `$('script[src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"]').length === 0`?

**Comment by jywarren** [comment]
Or, I think we could just add to the docs that jquery is needed -- it's especially bad when jquery is loaded multiple times because it can cancel out listeners (like, it breaks toggles, for example, by clicking twice).

We mention the requirement of jquery in PublicLab.Editor, so I think it's OK here too!

**Comment by Dsxv** [comment]
Hi @jywarren  @sagarpreet-chadha @kevinzluo ! Is this still  on ? I'd like to take on this .
Thanks!

**Comment by gauravano** [comment]
@Dsxv please go ahead! Thanks!

**Comment by rkpattnaik780** [comment]
I have implemented a possible solution, shall I make the PR for it?

**Comment by jywarren** [comment]
Yes please!

**Comment by rkpattnaik780** [comment]
Hello Everyone, I have been [working](https://github.com/publiclab/leaflet-environmental-layers/pull/125) on this issue since quiet some time . I have made a few observations that I would like to mention in the thread.

I was going through the `SkyTruthLayer` and I observed certain peculiarities in the implementation of the `requestData()` method :- 

 
![image](https://user-images.githubusercontent.com/23582438/54081579-18ca2100-432d-11e9-83b6-d56261eb2a4e.png)


To fix the issue, I had thought of checking whether jQuery is already loaded in the `<head>`, but what I realize is the `script.onload` method won't be fired till script is appended to the html. And moreover, in line 29,316, we are initializing jQuery, so it must be already present in the `<head>`. I had an idea that maybe we do not need to create a `script` at all in line 29,311, which will allow us to get the data even without appending the jQuery script to head. And it worked.

![image](https://user-images.githubusercontent.com/23582438/54081625-ac035680-432d-11e9-8878-52d2e3c6a064.png)

Commenting out any mention of the script tag works just fine, without appending additional jQuery scripts to HTML. I feel that maybe initializing a script like that is unnecessary for some of the layers. I noticed the exact same thing for `FrackTrackerLayer` as well I am bit new to the codebase, please let me know if I am missing out something or should I carry out this implementation for other layers as well.

**Comment by jywarren** [comment]
I agree - actually i think that we can just say in the docs that you should
have jquery installed and included separately, and we should not try to
include it automatically anywhere. I think this will simplify things a lot!
Thank you!!!

**Comment by rkpattnaik780** [comment]
@jywarren Thank you. I will update the pull request soon. :)
